In [1]:
import pandas as pd

In [48]:
dict1 = {'names': ['Ali', 'Ayse', 'Burak', 'Deniz', 'Grok'], 'ages': [25, 20, 27, 22, 18], 'grades': [90, 85, 75, 85, 100]}

In [49]:
data = pd.DataFrame(dict1)
data

   names  ages  grades
0    Ali    25      90
1   Ayse    20      85
2  Burak    27      75
3  Deniz    22      85
4   Grok    18     100

In [50]:
data['names'].count()

np.int64(5)

In [51]:
targetAudience = data.query('ages > 25 and names != "Ali"')
targetAudience

   names  ages  grades
2  Burak    27      75

In [52]:
secim = data[(data["ages"] > ~23) & (data["names"] == "Ali")]
secim

  names  ages  grades
0   Ali    25      90

In [53]:
if (4 == 4) & (1 > 2):
    print("oldu")

In [64]:
data.iloc[1:5:2,0:2]

   names  ages
1   Ayse    20
3  Deniz    22

In [66]:
veri = {
"cinsiyet": ["K", "E", "K", "E"],
"puan": [85, 70, 90, 60]
}
df = pd.DataFrame(veri)
grup = df.groupby("cinsiyet")["puan"].mean()
print(grup)

cinsiyet
E    65.0
K    87.5
Name: puan, dtype: float64

In [68]:
istatistikler = df.groupby("cinsiyet").agg(
ortalama_puan = ("puan", "mean"),
en_yuksek_puan = ("puan", "max"),
kisi_sayisi = ("puan", "count")
)
print(istatistikler)

          ortalama_puan  en_yuksek_puan  kisi_sayisi
cinsiyet
E                  65.0              70            2
K                  87.5              90            2

In [1]:
import pandas as pd

df = pd.DataFrame({
    "yas": [20, 30, 40, 85],
    "puan": [80, 70, 90, 85]
})
print(df.describe())

             yas       puan
count   4.000000   4.000000
mean   43.750000  81.250000
std    28.686524   8.539126
min    20.000000  70.000000
25%    27.500000  77.500000
50%    35.000000  82.500000
75%    51.250000  86.250000
max    85.000000  90.000000